# Author: Stian Skogbrott
# SPDX-License-Identifier: BUSL-1.1
"""``remora init-review``: generate a complete strict-profile configuration.

The strict runtime profiles refuse to start until a signed ToolSpec bundle,
a registry module, durable state, signing keys, a custody split and an
intent resolver are all in place. Every one of those is load-bearing, and
none of them is negotiable. What is negotiable is how much typing it takes
to reach a configuration that satisfies them.

This module writes that configuration, in the shape the invariants demand:

* three environment files, one per custody domain, and never two domains in
  one file. The authority holds signing material and no effect credential.
  The executor runs tool code and holds neither signing material nor an
  effect credential. The effect domain holds the effect credential and runs
  only the primitives mediated effects need (CR-005);
* a registry module with one mediated demo tool whose one effect writes to a
  local file, so the chain can be exercised end to end without a network;
* a ToolSpec bundle for that tool (schema version 3, ``effect_mode:
  MEDIATED``), signed with the generated key, and a capability policy that
  grants it;
* an intent source, so the property-D floor has something to resolve;
* a SQLite path for durable state, and a .gitignore that keeps keys, env
  files and state out of version control.

It automates ceremony. It removes no invariant: the result must still pass
``remora doctor`` and ``validate_runtime_profile_prerequisites`` on its own
merits, and the tests in ``tests/test_init_review_scaffold.py`` assert that.
"""
from __future__ import annotations

import hashlib
import inspect
import json
import os
import secrets
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

__all__ = ["ScaffoldExists", "init_review"]

SIGNING_IDENTITY = "local-review-signer/v1"
DEMO_TOOL = "send_notification"
#: Where the executor reaches the effect domain (``remora serve --port 8012``).
EFFECT_ENDPOINT = "http://127.0.0.1:8012"


class ScaffoldExists(FileExistsError):
    """The target directory already holds a scaffold; refuse to overwrite keys."""


# The demo callable, written verbatim into the registry module. Its source
# is what the ToolSpec's callable_digest attests, so it lives here as text
# rather than being reconstructed at scaffold time.
_REGISTRY_SOURCE = '''# Generated by `remora init-review`. Replace the demo tool with your own.
#
# Contract (CR-005, three domains):
# - register_tools(register): the EXECUTOR calls register(tool_id, fn,
#   mediated=True) for every tool it may dispatch. Each fn takes the argument
#   dict and a capability mediator, and reaches effects only through
#   capabilities.invoke(capability, resource, arguments). Tool code holds no
#   effect credential: the executor process has none to hold.
# - register_effect_executors(bind): the EFFECT DOMAIN binds one primitive
#   per capability. Primitives close over the effect credential, which lives
#   in that process and nowhere else.
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path

OUTBOX_RESOURCE = "notification://outbox"


def send_notification(arguments: dict, capabilities) -> dict:
    """Demo tool: ask the mediator for one notification.send effect."""
    effect = capabilities.invoke("notification.send", OUTBOX_RESOURCE, {
        "to": arguments.get("to", ""), "subject": arguments.get("subject", "")})
    return {"status": effect.state.value, "to": arguments.get("to", ""),
            "refusal": effect.refusal}


def register_tools(register) -> None:
    register("send_notification", send_notification, mediated=True)


def _effect_credential() -> str:
    names = os.environ.get("REMORA_EFFECT_CREDENTIAL_ENV_NAMES", "").split(",")
    return os.environ.get(names[0].strip(), "") if names[0].strip() else ""


def deliver_notification(resource: str, arguments) -> dict:
    """Demo effect: append the notification to a local outbox file.

    Stands in for SMTP or a vendor API. It reads the effect credential the
    way a real primitive would, so the custody split is exercised for real:
    only the effect domain holds it.
    """
    if not _effect_credential():
        raise RuntimeError("effect credential not present in this process")
    outbox = Path(os.environ.get("REMORA_DEMO_OUTBOX", ".remora/state/outbox.jsonl"))
    outbox.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "to": arguments.get("to", ""),
        "subject": arguments.get("subject", ""),
        "delivered_at": datetime.now(timezone.utc).isoformat(),
    }
    with outbox.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record) + "\\n")
    return {"status": "delivered", "to": record["to"]}


def register_effect_executors(bind) -> None:
    bind({"notification.send": deliver_notification})
'''


_EFFECTS_SOURCE = '''
"""Closed effect registry for the demo tool (CR-006: resolved_effect REQUIRED).

A consequential tool needs a real resolver under a strict profile. This one
knows exactly one tool and one effect; anything else is an unresolved
reference and refuses.
"""
from remora.enforcement.resolved_effect import ClosedWorldResolver


def build_resolver():
    return ClosedWorldResolver(
        tools={"send_notification": ("remora_registry.send_notification@v1", "send")},
        resources={},
        resource_argument={},
    )
'''

_BINDING_POLICY = """\
# BindingPolicy for review/v2 (CR-006). Every binding is stated; implicit is
# a startup failure. States: REQUIRED (compared at dispatch, its comparator
# must exist), NOT_APPLICABLE (per tool, resolved_effect only, read-only tools
# only), UNVERIFIABLE (a declared gap, recorded at startup, non-core only).
schema: remora-binding-policy/v1
bindings:
  exact_call: REQUIRED
  toolspec: REQUIRED
  tenant: REQUIRED
  actor: REQUIRED
  audience: REQUIRED
  runtime_surface: REQUIRED
  resolved_effect: REQUIRED      # remora_effects.build_resolver
  capability_set: REQUIRED       # REMORA_CAPABILITY_POLICY_FILE
  effect_mediation: REQUIRED     # signed effect_mode, REMORA_EFFECT_ENDPOINT
  # Declared gap for the demo: its calls name no A2A task. Set REQUIRED once
  # callers send context_id/task_id.
  task_identity: UNVERIFIABLE
tools: {}
"""


def _callable_digest(source: str) -> str:
    return "sha256:" + hashlib.sha256(source.encode("utf-8")).hexdigest()


def _demo_spec(callable_digest: str) -> dict[str, Any]:
    description = "Send a notification to one recipient (demo: local outbox file)."
    return {
        "tool_id": DEMO_TOOL,
        "version": 1,
        "callable_digest": callable_digest,
        "implementation_identity": "remora_registry.send_notification@scaffold",
        "description": description,
        "description_sha256": hashlib.sha256(description.encode("utf-8")).hexdigest(),
        "argument_schema": {
            "type": "object",
            "properties": {
                "to": {"type": "string"},
                "subject": {"type": "string"},
            },
            "required": ["to"],
            "additionalProperties": False,
        },
        "risk_tier": "medium",
        "action_type": "write",
        "domain": "general",
        "capabilities": ["notification"],
        "semantic_contract": {
            "capability": "notification",
            "effect": "create",
            "resource_type": "notification",
            "mutation": True,
            "argument_roles": {"to": "target_resource"},
        },
        "credential_scope": ["notify:send"],
        "allowed_targets": ["staging", "prod"],
        "idempotency_contract": {"safe_to_retry": False, "key_derivation": "canonical_args"},
        "postcondition_reader": "http",
        "compensation_tool": None,
        "timeout_policy": {"dispatch_timeout_seconds": 15},
        "network_policy": {"egress": "none"},
        "signing_identity": SIGNING_IDENTITY,
        # Schema version 3 (CR-005): every effect goes through the mediator,
        # within this ceiling, on a credential the effect domain holds.
        "effect_mode": "MEDIATED",
        "downstream_capabilities": [{
            "capability": "notification.send",
            "resources": ["notification://outbox"],
            "purpose": "deliver_notification",
        }],
        "credential_policy": {"direct_effect_credentials": "FORBIDDEN"},
    }


def _capability_policy() -> dict[str, Any]:
    """The demo grant: the local agent may send notifications in both targets."""
    tools = [DEMO_TOOL]
    return {
        "policy_version": "scaffold-1",
        "registry_version": "scaffold-1",
        "registry": {DEMO_TOOL: ["staging", "prod"]},
        "principals": {"local-agent": tools},
        "tasks": {"notify": tools},
        "tenants": {"default": tools},
        "environments": {"staging": tools, "prod": tools},
    }


def _ed25519_keypair() -> tuple[str, str | None]:
    """(seed_hex, public_hex). Public is None when 'cryptography' is absent."""
    seed = os.urandom(32)
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ed25519
    except ImportError:
        return seed.hex(), None
    public = ed25519.Ed25519PrivateKey.from_private_bytes(seed).public_key()
    raw = public.public_bytes(
        encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw
    )
    return seed.hex(), raw.hex()


def _env_file(lines: list[tuple[str, str]], header: str) -> str:
    body = "\n".join(f"export {k}={_quote(v)}" for k, v in lines)
    return f"{header}\n{body}\n"


def _quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def init_review(
    root: str | os.PathLike[str] = ".remora",
    *,
    effect_credential_name: str = "ACME_NOTIFY_API_KEY",
    force: bool = False,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Write a complete strict-profile configuration under ``root``.

    Returns a summary: the paths written, the signing identity, and whether
    an Ed25519 public key could be derived (without it the executor env is
    written with a placeholder, and says so).
    """
    base = Path(root)
    keys_dir = base / "keys"
    if keys_dir.exists() and any(keys_dir.iterdir()) and not force:
        raise ScaffoldExists(
            f"{keys_dir} already holds keys; pass force=True to regenerate "
            "them (existing leases and tokens will stop verifying)"
        )
    for sub in ("keys", "state"):
        (base / sub).mkdir(parents=True, exist_ok=True)
    os.chmod(base / "keys", 0o700)

    stamp = (now or datetime.now(timezone.utc)).isoformat()
    written: list[Path] = []

    def put(rel: str, content: str, *, secret: bool = False) -> Path:
        path = base / rel
        if secret:
            # Owner-only from the first byte: create with 0o600 rather than
            # write-then-chmod, so there is no window where the default umask
            # leaves a signing key or credential readable to other users.
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
            os.chmod(path, 0o600)
        else:
            path.write_text(content, encoding="utf-8")
        written.append(path)
        return path

    # -- secrets ------------------------------------------------------------
    pdp_key = secrets.token_hex(32)
    envelope_key = secrets.token_hex(32)
    audit_key = secrets.token_hex(32)
    execution_token = secrets.token_hex(24)
    # Transport bearer from the executor to the effect domain. Not an
    # authority credential: the effect domain still verifies the lease.
    effect_token = secrets.token_hex(24)
    # RMR-CR-003: a strict profile derives tenant and role from a credential
    # table, never from headers. Two callers on the authority (the agent and a
    # human reviewer, so proposer and approver are different principals) and
    # one on the executor (the authority's internal dispatch hop).
    operator_token = secrets.token_hex(24)
    reviewer_token = secrets.token_hex(24)
    authority_api_tokens = json.dumps({
        operator_token: {"tenant": "default", "role": "operator", "actor_id": "local-agent"},
        reviewer_token: {"tenant": "default", "role": "reviewer", "actor_id": "local-reviewer"},
    }, sort_keys=True)
    executor_api_tokens = json.dumps({
        execution_token: {"tenant": "default", "role": "operator",
                          "actor_id": "authority-dispatch-hop"},
    }, sort_keys=True)
    effect_api_tokens = json.dumps({
        effect_token: {"tenant": "default", "role": "operator",
                       "actor_id": "executor-effect-hop"},
    }, sort_keys=True)
    effect_credential = "demo-" + secrets.token_hex(16)
    lease_seed, lease_public = _ed25519_keypair()
    kid = "review-" + stamp[:10]

    # -- registry, bundle, intents ------------------------------------------
    registry_path = put("remora_registry.py", _REGISTRY_SOURCE)
    put("remora_effects.py", inspect.cleandoc(_EFFECTS_SOURCE) + "\n")
    policy_path = put("binding-policy.yaml", _BINDING_POLICY)
    capability_path = put("capability-policy.json",
                          json.dumps(_capability_policy(), indent=2, sort_keys=True) + "\n")
    digest = _callable_digest(inspect.cleandoc(_REGISTRY_SOURCE))
    # RMR-CR-001: the bundle is signed here, at authoring time, with an Ed25519
    # seed that goes only to keys/. Neither runtime half receives it; both get
    # the public key and the pinned digest, so neither can author a bundle.
    try:
        from remora.toolcall.toolspec_sign import sign_with_seed
    except ImportError as exc:  # pragma: no cover - cryptography is a dev dependency
        raise RuntimeError(
            "init-review signs the ToolSpec bundle with Ed25519 and needs the "
            "'cryptography' package: pip install 'remora[security]'"
        ) from exc
    toolspec_seed = secrets.token_hex(32)
    bundle, toolspec_public, toolspec_digest = sign_with_seed(
        {"schema_version": 3, "tool_specs": [_demo_spec(digest)]},
        toolspec_seed, signed_at=stamp,
    )
    signing_identity = bundle["registry_signature"]["signing_identity"]
    bundle_path = put("toolspec-bundle.json", json.dumps(bundle, indent=2, sort_keys=True) + "\n")
    intents_path = put("workflow_intents.json", json.dumps({
        "wo-demo-1": {
            "task_text": "Send a notification to ops@example.com about the deploy.",
            "operation": "create",
            "resource_type": "notification",
            "requested_effect": "create",
            "target_entities": ["ops@example.com"],
            "source_spans": ["ops@example.com"],
            "action_spans": ["send a notification"],
        }
    }, indent=2) + "\n")
    chain_db = base / "state" / "execution.db"

    # -- keys on disk (executor never reads these files) -----------------------
    for name, value in (
        ("pdp_signing_key", pdp_key), ("envelope_signing_key", envelope_key),
        ("audit_signing_key", audit_key),
        # Offline signer material: re-sign the bundle with it, never load it.
        ("toolspec_ed25519_seed", toolspec_seed),
        ("lease_ed25519_seed", lease_seed),
        ("operator_token", operator_token), ("reviewer_token", reviewer_token),
    ):
        put(f"keys/{name}", value + "\n", secret=True)
    if lease_public:
        put("keys/lease_ed25519_public", lease_public + "\n", secret=True)

    shared: list[tuple[str, str]] = [
        ("REMORA_RUNTIME_PROFILE", "review"),
        ("REMORA_ENABLED_SURFACES", "execution"),
        ("REMORA_EFFECT_CREDENTIAL_ENV_NAMES", effect_credential_name),
        ("REMORA_TOOLSPEC_BUNDLE", str(bundle_path.resolve())),
        ("REMORA_TOOLSPEC_VERIFY_KEYS", toolspec_public),
        ("REMORA_BINDING_POLICY", str(policy_path.resolve())),
        ("REMORA_CAPABILITY_POLICY_FILE", str(capability_path.resolve())),
        ("REMORA_EFFECT_REGISTRY_MODULE", "remora_effects"),
        ("REMORA_TOOLSPEC_PINNED_DIGEST", toolspec_digest),
        ("REMORA_TOOL_REGISTRY_MODULE", "remora_registry"),
        ("REMORA_SEMANTIC_BUNDLE_MODULE", "servers.semantic_bundle_research"),
        ("REMORA_INTENT_SOURCE_FILE", str(intents_path.resolve())),
        ("REMORA_CHAIN_DB", str(chain_db.resolve())),
        ("REMORA_DEMO_OUTBOX", str((base / "state" / "outbox.jsonl").resolve())),
        ("PYTHONPATH", str(base.resolve())),
    ]

    # -- authority: signs, never holds the effect credential --------------------
    authority = shared + [
        ("REMORA_EXECUTION_DOMAIN_ROLE", "authority"),
        ("REMORA_PDP_SIGNING_KEY", pdp_key),
        ("REMORA_ENVELOPE_SIGNING_KEY", envelope_key),
        ("REMORA_AUDIT_SIGNING_KEY", audit_key),
        ("REMORA_LEASE_SIGNING_KEY_ED25519_PRIVATE", lease_seed),
        ("REMORA_LEASE_SIGNING_KID", kid),
        ("REMORA_EXECUTION_TOKEN", execution_token),
        ("REMORA_API_TOKENS", authority_api_tokens),
    ]
    put("authority.env", secret=True, content=_env_file(authority,
        "# Generated by `remora init-review`. The AUTHORITY half of the custody split.\n"
        "# Holds signing material. Holds NO effect credential, by requirement: a\n"
        "# process that authorizes and performs needs no bypass to be bypassed.\n"
        "# Load with:  set -a; . .remora/authority.env; set +a"))

    verify_key = lease_public or "REPLACE-ME: install the 'security' extra and re-run init-review"

    # -- executor: runs tool code, holds no credential and only the public key --
    executor = shared + [
        ("REMORA_EXECUTION_DOMAIN_ROLE", "executor"),
        ("REMORA_EFFECT_ENDPOINT", EFFECT_ENDPOINT),
        ("REMORA_EFFECT_TOKEN", effect_token),
        ("REMORA_LEASE_VERIFY_KEY_ED25519_PUBLIC", verify_key),
        ("REMORA_LEASE_SIGNING_KID", kid),
        ("REMORA_EXECUTION_TOKEN", execution_token),
        ("REMORA_API_TOKENS", executor_api_tokens),
    ]
    put("executor.env", secret=True, content=_env_file(executor,
        "# Generated by `remora init-review`. The EXECUTION domain of the custody split.\n"
        "# Runs tool code and holds the lease PUBLIC key. Holds no signing key (a\n"
        "# process that can sign its own authorization verifies nothing) and no\n"
        "# effect credential (tool code here could use it without the mediator).\n"
        "# Load with:  set -a; . .remora/executor.env; set +a"))

    # -- effect domain: holds the credential, runs primitives, no tool code -----
    effect = shared + [
        ("REMORA_EXECUTION_DOMAIN_ROLE", "effect"),
        (effect_credential_name, effect_credential),
        ("REMORA_LEASE_VERIFY_KEY_ED25519_PUBLIC", verify_key),
        ("REMORA_LEASE_SIGNING_KID", kid),
        ("REMORA_API_TOKENS", effect_api_tokens),
    ]
    put("effect.env", secret=True, content=_env_file(effect,
        "# Generated by `remora init-review`. The EFFECT domain of the custody split.\n"
        "# Holds the effect credential and the lease PUBLIC key, and serves only\n"
        "# /v1/execution/effects: it runs the primitives mediated effects need,\n"
        "# for leases the executor has dispatched, within the signed ceiling.\n"
        "# Load with:  set -a; . .remora/effect.env; set +a"))

    put(".gitignore", "keys/\n*.env\nstate/\n")
    put("README.md",
        "# Local review configuration\n\n"
        "Generated by `remora init-review`. Three processes, three env files, one\n"
        "custody split.\n\n"
        "```bash\n"
        "set -a; . .remora/authority.env; set +a\n"
        "remora doctor            # every strict prerequisite, named\n"
        "remora serve             # the authority: /v1/execution/*\n\n"
        "# second shell\n"
        "set -a; . .remora/executor.env; set +a\n"
        "remora serve --port 8011 # the execution domain: tool code, no credential\n\n"
        "# third shell\n"
        "set -a; . .remora/effect.env; set +a\n"
        "remora serve --port 8012 # the effect domain: the credential, no tool code\n"
        "```\n\n"
        f"The demo tool `{DEMO_TOOL}` is mediated: it asks for one\n"
        "`notification.send` effect, which the effect domain performs by\n"
        "appending to `state/outbox.jsonl` instead of sending anything. The\n"
        "executor and the effect domain share `state/execution.db`, which is how\n"
        "the effect domain knows a lease was dispatched; on separate hosts use\n"
        "REMORA_PG_DSN instead. Replace `remora_registry.py` with your own tools\n"
        "and re-sign the bundle offline:\n\n"
        "```bash\n"
        "python -m remora.toolcall.toolspec_sign --seed-file .remora/keys/toolspec_ed25519_seed \\\n"
        "    --bundle unsigned.json --out .remora/toolspec-bundle.json\n"
        "```\n\n"
        "It prints the new REMORA_TOOLSPEC_VERIFY_KEYS and REMORA_TOOLSPEC_PINNED_DIGEST\n"
        "for every env file. Keep the seed off all runtime hosts, and keep the\n"
        "three env files on three different hosts.\n")

    return {
        "root": str(base.resolve()),
        "written": [str(p) for p in written],
        "signing_identity": signing_identity,
        "toolspec_bundle_digest": toolspec_digest,
        "ed25519_public_derived": lease_public is not None,
        "registry_module": "remora_registry",
        "registry_path": str(registry_path),
    }
