# Author: Stian Skogbrott
# SPDX-License-Identifier: BUSL-1.1
"""``remora init-review``: generate a complete strict-profile configuration.

The strict runtime profiles refuse to start until a signed ToolSpec bundle,
a registry module, durable state, signing keys, a custody split and an
intent resolver are all in place. Every one of those is load-bearing, and
none of them is negotiable. What is negotiable is how much typing it takes
to reach a configuration that satisfies them.

This module writes that configuration, in the shape the invariants demand:

* two environment files, one per custody half, and never both halves in
  one file. The authority holds signing material and no effect credential;
  the executor holds the effect credential and only the public key;
* a registry module with one demo tool that writes to a local file, so the
  chain can be exercised end to end without a network;
* a ToolSpec bundle for that tool, signed with the generated key;
* an intent source, so the property-D floor has something to resolve;
* a SQLite path for durable state, and a .gitignore that keeps keys, env
  files and state out of version control.

It automates ceremony. It removes no invariant: the result must still pass
``remora doctor`` and ``validate_runtime_profile_prerequisites`` on its own
merits, and the tests in ``tests/test_init_review_scaffold.py`` assert that.
"""
from __future__ import annotations

import hashlib
import inspect
import json
import os
import secrets
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

__all__ = ["ScaffoldExists", "init_review"]

SIGNING_IDENTITY = "local-review-signer/v1"
DEMO_TOOL = "send_notification"


class ScaffoldExists(FileExistsError):
    """The target directory already holds a scaffold; refuse to overwrite keys."""


# The demo callable, written verbatim into the registry module. Its source
# is what the ToolSpec's callable_digest attests, so it lives here as text
# rather than being reconstructed at scaffold time.
_REGISTRY_SOURCE = '''# Generated by `remora init-review`. Replace the demo tool with your own.
#
# Contract: expose register_tools(register); call register(tool_id, fn) for
# every tool the execution domain may dispatch. Each fn takes the argument
# dict and returns a JSON-serialisable result. The credential a tool needs
# belongs in THIS process (the executor), read here and nowhere else.
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path


def send_notification(arguments: dict) -> dict:
    """Demo effect: append the notification to a local outbox file.

    Stands in for SMTP or a vendor API. It reads the effect credential the
    same way a real tool would, so the custody split is exercised for real:
    in the authority process this variable is absent by requirement.
    """
    credential = os.environ.get("EFFECT_CREDENTIAL_NAME", "")
    if not credential:
        raise RuntimeError("effect credential not present in this process")
    outbox = Path(os.environ.get("REMORA_DEMO_OUTBOX", ".remora/state/outbox.jsonl"))
    outbox.parent.mkdir(parents=True, exist_ok=True)
    record = {
        "to": arguments.get("to", ""),
        "subject": arguments.get("subject", ""),
        "delivered_at": datetime.now(timezone.utc).isoformat(),
    }
    with outbox.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(record) + "\\n")
    return {"status": "delivered", "to": record["to"]}


def register_tools(register) -> None:
    register("send_notification", send_notification)
'''


def _callable_digest(source: str) -> str:
    return "sha256:" + hashlib.sha256(source.encode("utf-8")).hexdigest()


def _demo_spec(callable_digest: str) -> dict[str, Any]:
    description = "Send a notification to one recipient (demo: local outbox file)."
    return {
        "tool_id": DEMO_TOOL,
        "version": 1,
        "callable_digest": callable_digest,
        "implementation_identity": "remora_registry.send_notification@scaffold",
        "description": description,
        "description_sha256": hashlib.sha256(description.encode("utf-8")).hexdigest(),
        "argument_schema": {
            "type": "object",
            "properties": {
                "to": {"type": "string"},
                "subject": {"type": "string"},
            },
            "required": ["to"],
            "additionalProperties": False,
        },
        "risk_tier": "medium",
        "action_type": "write",
        "domain": "general",
        "capabilities": ["notification"],
        "semantic_contract": {
            "capability": "notification",
            "effect": "create",
            "resource_type": "notification",
            "mutation": True,
            "argument_roles": {"to": "target_resource"},
        },
        "credential_scope": ["notify:send"],
        "allowed_targets": ["staging", "prod"],
        "idempotency_contract": {"safe_to_retry": False, "key_derivation": "canonical_args"},
        "postcondition_reader": "http",
        "compensation_tool": None,
        "timeout_policy": {"dispatch_timeout_seconds": 15},
        "network_policy": {"egress": "none"},
        "signing_identity": SIGNING_IDENTITY,
    }


def _ed25519_keypair() -> tuple[str, str | None]:
    """(seed_hex, public_hex). Public is None when 'cryptography' is absent."""
    seed = os.urandom(32)
    try:
        from cryptography.hazmat.primitives import serialization
        from cryptography.hazmat.primitives.asymmetric import ed25519
    except ImportError:
        return seed.hex(), None
    public = ed25519.Ed25519PrivateKey.from_private_bytes(seed).public_key()
    raw = public.public_bytes(
        encoding=serialization.Encoding.Raw, format=serialization.PublicFormat.Raw
    )
    return seed.hex(), raw.hex()


def _env_file(lines: list[tuple[str, str]], header: str) -> str:
    body = "\n".join(f"export {k}={_quote(v)}" for k, v in lines)
    return f"{header}\n{body}\n"


def _quote(value: str) -> str:
    return "'" + value.replace("'", "'\\''") + "'"


def init_review(
    root: str | os.PathLike[str] = ".remora",
    *,
    effect_credential_name: str = "ACME_NOTIFY_API_KEY",
    force: bool = False,
    now: datetime | None = None,
) -> dict[str, Any]:
    """Write a complete strict-profile configuration under ``root``.

    Returns a summary: the paths written, the signing identity, and whether
    an Ed25519 public key could be derived (without it the executor env is
    written with a placeholder, and says so).
    """
    base = Path(root)
    keys_dir = base / "keys"
    if keys_dir.exists() and any(keys_dir.iterdir()) and not force:
        raise ScaffoldExists(
            f"{keys_dir} already holds keys; pass force=True to regenerate "
            "them (existing leases and tokens will stop verifying)"
        )
    for sub in ("keys", "state"):
        (base / sub).mkdir(parents=True, exist_ok=True)
    os.chmod(base / "keys", 0o700)

    stamp = (now or datetime.now(timezone.utc)).isoformat()
    written: list[Path] = []

    def put(rel: str, content: str, *, secret: bool = False) -> Path:
        path = base / rel
        if secret:
            # Owner-only from the first byte: create with 0o600 rather than
            # write-then-chmod, so there is no window where the default umask
            # leaves a signing key or credential readable to other users.
            fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
            os.chmod(path, 0o600)
        else:
            path.write_text(content, encoding="utf-8")
        written.append(path)
        return path

    # -- secrets ------------------------------------------------------------
    pdp_key = secrets.token_hex(32)
    envelope_key = secrets.token_hex(32)
    audit_key = secrets.token_hex(32)
    toolspec_key = secrets.token_hex(32)
    execution_token = secrets.token_hex(24)
    effect_credential = "demo-" + secrets.token_hex(16)
    lease_seed, lease_public = _ed25519_keypair()
    kid = "review-" + stamp[:10]

    # -- registry, bundle, intents ------------------------------------------
    registry_path = put("remora_registry.py", _REGISTRY_SOURCE)
    digest = _callable_digest(inspect.cleandoc(_REGISTRY_SOURCE))
    from remora.toolcall.toolspec import sign_bundle

    bundle = sign_bundle(
        {"schema_version": 1, "tool_specs": [_demo_spec(digest)]},
        key=toolspec_key, signing_identity=SIGNING_IDENTITY, signed_at=stamp,
    )
    bundle_path = put("toolspec-bundle.json", json.dumps(bundle, indent=2, sort_keys=True) + "\n")
    intents_path = put("workflow_intents.json", json.dumps({
        "wo-demo-1": {
            "task_text": "Send a notification to ops@example.com about the deploy.",
            "operation": "create",
            "resource_type": "notification",
            "requested_effect": "create",
            "target_entities": ["ops@example.com"],
            "source_spans": ["ops@example.com"],
            "action_spans": ["send a notification"],
        }
    }, indent=2) + "\n")
    chain_db = base / "state" / "execution.db"

    # -- keys on disk (executor never reads these files) -----------------------
    for name, value in (
        ("pdp_signing_key", pdp_key), ("envelope_signing_key", envelope_key),
        ("audit_signing_key", audit_key), ("toolspec_signing_key", toolspec_key),
        ("lease_ed25519_seed", lease_seed),
    ):
        put(f"keys/{name}", value + "\n", secret=True)
    if lease_public:
        put("keys/lease_ed25519_public", lease_public + "\n", secret=True)

    shared: list[tuple[str, str]] = [
        ("REMORA_RUNTIME_PROFILE", "review"),
        ("REMORA_ENABLED_SURFACES", "execution"),
        ("REMORA_EFFECT_CREDENTIAL_ENV_NAMES", effect_credential_name),
        ("REMORA_TOOLSPEC_BUNDLE", str(bundle_path.resolve())),
        ("REMORA_TOOLSPEC_TRUSTED_IDENTITIES", SIGNING_IDENTITY),
        ("REMORA_TOOL_REGISTRY_MODULE", "remora_registry"),
        ("REMORA_SEMANTIC_BUNDLE_MODULE", "servers.semantic_bundle_research"),
        ("REMORA_INTENT_SOURCE_FILE", str(intents_path.resolve())),
        ("REMORA_CHAIN_DB", str(chain_db.resolve())),
        ("REMORA_DEMO_OUTBOX", str((base / "state" / "outbox.jsonl").resolve())),
        ("PYTHONPATH", str(base.resolve())),
    ]

    # -- authority: signs, never holds the effect credential --------------------
    authority = shared + [
        ("REMORA_EXECUTION_DOMAIN_ROLE", "authority"),
        ("REMORA_TOOLSPEC_SIGNING_KEY", toolspec_key),
        ("REMORA_PDP_SIGNING_KEY", pdp_key),
        ("REMORA_ENVELOPE_SIGNING_KEY", envelope_key),
        ("REMORA_AUDIT_SIGNING_KEY", audit_key),
        ("REMORA_LEASE_SIGNING_KEY_ED25519_PRIVATE", lease_seed),
        ("REMORA_LEASE_SIGNING_KID", kid),
        ("REMORA_EXECUTION_TOKEN", execution_token),
    ]
    put("authority.env", secret=True, content=_env_file(authority,
        "# Generated by `remora init-review`. The AUTHORITY half of the custody split.\n"
        "# Holds signing material. Holds NO effect credential, by requirement: a\n"
        "# process that authorizes and performs needs no bypass to be bypassed.\n"
        "# Load with:  set -a; . .remora/authority.env; set +a"))

    # -- executor: holds the credential and only the public key ----------------
    executor = shared + [
        ("REMORA_EXECUTION_DOMAIN_ROLE", "executor"),
        (effect_credential_name, effect_credential),
        ("EFFECT_CREDENTIAL_NAME", effect_credential),
        ("REMORA_LEASE_VERIFY_KEY_ED25519_PUBLIC",
         lease_public or "REPLACE-ME: install the 'security' extra and re-run init-review"),
        ("REMORA_LEASE_SIGNING_KID", kid),
        ("REMORA_EXECUTION_TOKEN", execution_token),
    ]
    put("executor.env", secret=True, content=_env_file(executor,
        "# Generated by `remora init-review`. The EXECUTOR half of the custody split.\n"
        "# Holds the effect credential and the lease PUBLIC key. Holds no signing\n"
        "# key: a process that can sign its own authorization verifies nothing.\n"
        "# Load with:  set -a; . .remora/executor.env; set +a"))

    put(".gitignore", "keys/\n*.env\nstate/\n")
    put("README.md",
        "# Local review configuration\n\n"
        "Generated by `remora init-review`. Two processes, two env files, one\n"
        "custody split.\n\n"
        "```bash\n"
        "set -a; . .remora/authority.env; set +a\n"
        "remora doctor            # every strict prerequisite, named\n"
        "remora serve             # the authority: /v1/execution/*\n\n"
        "# second shell\n"
        "set -a; . .remora/executor.env; set +a\n"
        "REMORA_EXECUTION_DOMAIN_ROLE=executor remora serve --port 8011\n"
        "```\n\n"
        f"The demo tool `{DEMO_TOOL}` appends to `state/outbox.jsonl` instead of\n"
        "sending anything. Replace `remora_registry.py` with your own tools, re-sign\n"
        "the bundle with `keys/toolspec_signing_key`, and keep the two env files\n"
        "on two different hosts.\n")

    return {
        "root": str(base.resolve()),
        "written": [str(p) for p in written],
        "signing_identity": SIGNING_IDENTITY,
        "ed25519_public_derived": lease_public is not None,
        "registry_module": "remora_registry",
        "registry_path": str(registry_path),
    }
