/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as PolicyRouteImport } from './routes/policy'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as LabRouteImport } from './routes/lab'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as EyeRouteImport } from './routes/eye'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ControlRoomRouteImport } from './routes/control-room'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as CascadeRouteImport } from './routes/cascade'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as AromerRouteImport } from './routes/aromer'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as ArticlesSlugRouteImport } from './routes/articles.$slug'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyRoute = PolicyRouteImport.update({
  id: '/policy',
  path: '/policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const EyeRoute = EyeRouteImport.update({
  id: '/eye',
  path: '/eye',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoomRoute = ControlRoomRouteImport.update({
  id: '/control-room',
  path: '/control-room',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const CascadeRoute = CascadeRouteImport.update({
  id: '/cascade',
  path: '/cascade',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AromerRoute = AromerRouteImport.update({
  id: '/aromer',
  path: '/aromer',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/architecture': typeof ArchitectureRoute
  '/aromer': typeof AromerRoute
  '/benchmarks': typeof BenchmarksRoute
  '/cascade': typeof CascadeRoute
  '/console': typeof ConsoleRoute
  '/control-room': typeof ControlRoomRoute
  '/evidence': typeof EvidenceRoute
  '/eye': typeof EyeRoute
  '/governance': typeof GovernanceRoute
  '/lab': typeof LabRoute
  '/operations': typeof OperationsRoute
  '/policy': typeof PolicyRoute
  '/scenarios': typeof ScenariosRoute
  '/telemetry': typeof TelemetryRoute
  '/whitepaper': typeof WhitepaperRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/architecture': typeof ArchitectureRoute
  '/aromer': typeof AromerRoute
  '/benchmarks': typeof BenchmarksRoute
  '/cascade': typeof CascadeRoute
  '/console': typeof ConsoleRoute
  '/control-room': typeof ControlRoomRoute
  '/evidence': typeof EvidenceRoute
  '/eye': typeof EyeRoute
  '/governance': typeof GovernanceRoute
  '/lab': typeof LabRoute
  '/operations': typeof OperationsRoute
  '/policy': typeof PolicyRoute
  '/scenarios': typeof ScenariosRoute
  '/telemetry': typeof TelemetryRoute
  '/whitepaper': typeof WhitepaperRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles': typeof ArticlesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/architecture': typeof ArchitectureRoute
  '/aromer': typeof AromerRoute
  '/benchmarks': typeof BenchmarksRoute
  '/cascade': typeof CascadeRoute
  '/console': typeof ConsoleRoute
  '/control-room': typeof ControlRoomRoute
  '/evidence': typeof EvidenceRoute
  '/eye': typeof EyeRoute
  '/governance': typeof GovernanceRoute
  '/lab': typeof LabRoute
  '/operations': typeof OperationsRoute
  '/policy': typeof PolicyRoute
  '/scenarios': typeof ScenariosRoute
  '/telemetry': typeof TelemetryRoute
  '/whitepaper': typeof WhitepaperRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/articles/': typeof ArticlesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/architecture'
    | '/aromer'
    | '/benchmarks'
    | '/cascade'
    | '/console'
    | '/control-room'
    | '/evidence'
    | '/eye'
    | '/governance'
    | '/lab'
    | '/operations'
    | '/policy'
    | '/scenarios'
    | '/telemetry'
    | '/whitepaper'
    | '/articles/$slug'
    | '/articles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/architecture'
    | '/aromer'
    | '/benchmarks'
    | '/cascade'
    | '/console'
    | '/control-room'
    | '/evidence'
    | '/eye'
    | '/governance'
    | '/lab'
    | '/operations'
    | '/policy'
    | '/scenarios'
    | '/telemetry'
    | '/whitepaper'
    | '/articles/$slug'
    | '/articles'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/architecture'
    | '/aromer'
    | '/benchmarks'
    | '/cascade'
    | '/console'
    | '/control-room'
    | '/evidence'
    | '/eye'
    | '/governance'
    | '/lab'
    | '/operations'
    | '/policy'
    | '/scenarios'
    | '/telemetry'
    | '/whitepaper'
    | '/articles/$slug'
    | '/articles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  AromerRoute: typeof AromerRoute
  BenchmarksRoute: typeof BenchmarksRoute
  CascadeRoute: typeof CascadeRoute
  ConsoleRoute: typeof ConsoleRoute
  ControlRoomRoute: typeof ControlRoomRoute
  EvidenceRoute: typeof EvidenceRoute
  EyeRoute: typeof EyeRoute
  GovernanceRoute: typeof GovernanceRoute
  LabRoute: typeof LabRoute
  OperationsRoute: typeof OperationsRoute
  PolicyRoute: typeof PolicyRoute
  ScenariosRoute: typeof ScenariosRoute
  TelemetryRoute: typeof TelemetryRoute
  WhitepaperRoute: typeof WhitepaperRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy': {
      id: '/policy'
      path: '/policy'
      fullPath: '/policy'
      preLoaderRoute: typeof PolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eye': {
      id: '/eye'
      path: '/eye'
      fullPath: '/eye'
      preLoaderRoute: typeof EyeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control-room': {
      id: '/control-room'
      path: '/control-room'
      fullPath: '/control-room'
      preLoaderRoute: typeof ControlRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cascade': {
      id: '/cascade'
      path: '/cascade'
      fullPath: '/cascade'
      preLoaderRoute: typeof CascadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aromer': {
      id: '/aromer'
      path: '/aromer'
      fullPath: '/aromer'
      preLoaderRoute: typeof AromerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  ArchitectureRoute: ArchitectureRoute,
  AromerRoute: AromerRoute,
  BenchmarksRoute: BenchmarksRoute,
  CascadeRoute: CascadeRoute,
  ConsoleRoute: ConsoleRoute,
  ControlRoomRoute: ControlRoomRoute,
  EvidenceRoute: EvidenceRoute,
  EyeRoute: EyeRoute,
  GovernanceRoute: GovernanceRoute,
  LabRoute: LabRoute,
  OperationsRoute: OperationsRoute,
  PolicyRoute: PolicyRoute,
  ScenariosRoute: ScenariosRoute,
  TelemetryRoute: TelemetryRoute,
  WhitepaperRoute: WhitepaperRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
