# Author: Stian Skogbrott
# SPDX-License-Identifier: BUSL-1.1
"""Render the superseded-claims archive from the claim register.

CLAUDE.md forbids deleting a result that a later round replaced. Keeping it in
the live register instead is the other failure mode: a reader meets a number
that the project itself no longer stands behind, with no signal that something
newer exists.

This generator resolves both. A claim marked ``status: superseded`` stays in
``claim_register_v1.yaml`` with its artifact, caveat and reproduce block intact,
and is additionally rendered here as an archive page that says, per claim, what
replaced it and why. ``scripts/check_claim_provenance.py`` enforces the other
half of the contract: a superseded claim may not stay anchored on the README
front page.

Usage:
    python scripts/generate_superseded_claims.py           # rewrite the page
    python scripts/generate_superseded_claims.py --check   # verify it is current
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from check_claim_provenance import parse_register  # noqa: E402

REGISTER = ROOT / "docs" / "assurance" / "claim_register_v1.yaml"
OUT = ROOT / "docs" / "assurance" / "superseded_claims.md"

HEADER = """<!-- GENERATED by scripts/generate_superseded_claims.py — DO NOT EDIT. -->
# Superseded claims

Results that a later round replaced. Nothing here was deleted: every claim keeps
its entry in [`claim_register_v1.yaml`](claim_register_v1.yaml) with its
artifact, caveat and reproduce block, and every artifact stays on disk. This page
is the archive view — the place to look when an older document, paper draft or
external write-up quotes a number this project has since moved past.

**A superseded claim is not a retracted claim.** It was measured, it is still
reproducible, and the observation it records still happened. What changed is that
a later, better-designed round now carries the load, so the newer claim is what
the README and the paper cite.

Superseded claims may not be anchored on the README front page; that rule is
enforced by `scripts/check_claim_provenance.py`, and this page is regenerated and
diffed in CI.

"""


def _rows(claims: list[dict]) -> list[dict]:
    return [c for c in claims if str(c.get("status", "active")) == "superseded"]


def render(claims: list[dict]) -> str:
    by_id = {c["id"]: c for c in claims if "id" in c}
    rows = _rows(claims)
    parts = [HEADER]

    if not rows:
        parts.append("_No claim is currently superseded._\n")
        return "".join(parts)

    parts.append("| Claim | What it said | Superseded by | Why |\n")
    parts.append("|-------|--------------|---------------|-----|\n")
    for claim in rows:
        cid = claim["id"]
        replacement = str(claim.get("superseded_by", "")).strip()
        newer = by_id.get(replacement)
        newer_title = newer["title"] if newer else replacement
        parts.append(
            f"| **{cid}** | {claim.get('title', '')} | "
            f"[{replacement}](claim_register_v1.yaml) — {newer_title} | "
            f"see below |\n"
        )

    parts.append("\n---\n\n")
    for claim in rows:
        cid = claim["id"]
        replacement = str(claim.get("superseded_by", "")).strip()
        parts.append(f"## {cid} — {claim.get('title', '')}\n\n")
        parts.append(f"**Superseded by:** {replacement}\n\n")
        parts.append(f"**Evidence level when archived:** `{claim.get('evidence_level')}`\n\n")
        parts.append(f"**Statement.** {claim.get('statement', '').strip()}\n\n")
        parts.append(f"**Caveat.** {claim.get('caveat', '').strip()}\n\n")
        artifacts = claim.get("artifact") or []
        if isinstance(artifacts, str):
            artifacts = [artifacts]
        listed = ", ".join(f"`{a}`" for a in artifacts)
        parts.append(f"**Artifacts (still on disk).** {listed}\n\n")
    return "".join(parts)


def main() -> int:
    claims = parse_register(REGISTER.read_text(encoding="utf-8"))
    rendered = render(claims)
    check = "--check" in sys.argv

    if check:
        if not OUT.exists():
            print(f"ERROR: {OUT.relative_to(ROOT)} does not exist; run the generator.")
            return 1
        current = OUT.read_text(encoding="utf-8").replace("\r\n", "\n")
        if current != rendered:
            print(
                f"ERROR: {OUT.relative_to(ROOT)} is stale — the claim register "
                f"has changed. Run: python scripts/generate_superseded_claims.py"
            )
            return 1
        n = len(_rows(claims))
        print(f"[OK] superseded-claims archive is current ({n} archived claim(s)).")
        return 0

    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"[OK] wrote {OUT.relative_to(ROOT)} ({len(_rows(claims))} archived claim(s)).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
